<a href="https://colab.research.google.com/github/Aniket1313/NLP/blob/master/Word_Embeddings_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Word Embedding Techniques using Embedding Layer in Keras,TF2.0

<li>Implementing simple word embeddings to understand Embedding Matrix</li>
<li>Libraries used Tensorflow 2.0 and keras</li>

Steps followed are :
<li>Sentences</li>
<li>One hot representations ==> fetch indexes from dictionary</li>
<li>One hot representation ==> Embedding Layer Keras To form Embedding Matrix</li>
<li>Embedding Matrix vocab_size=10000,dimension =10</li>


In [0]:
#tensorflow 2.0
from tensorflow.keras.preprocessing.text import one_hot

In [0]:
### Sentences

sent = ["the glass of milk",
        "the glass of juice",
        "the cup of tea",
        "I am a good boy",
        "I am a good developer",
        "understand the meaning of words",
        "your videos are good"]

In [12]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [0]:
##vocabulary size
voc_size =10000 ##size of dictionary

## One Hot Representation

In [14]:
onehot_representation =[one_hot(words,voc_size) for words in sent]
print(onehot_representation)

[[7975, 6669, 9441, 2948], [7975, 6669, 9441, 6185], [7975, 8609, 9441, 1696], [8315, 2736, 9568, 7559, 2883], [8315, 2736, 9568, 7559, 2184], [7639, 7975, 7089, 9441, 3042], [6295, 8883, 7242, 7559]]


## Word Embedding Representation

In [0]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [0]:
import numpy as np

In [17]:
sent_length=8
embedded_docs = pad_sequences(onehot_representation,padding ='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7975 6669 9441 2948]
 [   0    0    0    0 7975 6669 9441 6185]
 [   0    0    0    0 7975 8609 9441 1696]
 [   0    0    0 8315 2736 9568 7559 2883]
 [   0    0    0 8315 2736 9568 7559 2184]
 [   0    0    0 7639 7975 7089 9441 3042]
 [   0    0    0    0 6295 8883 7242 7559]]


In [0]:
dim =10

In [0]:
model =Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [22]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [23]:
print(model.predict(embedded_docs))

[[[-0.01706602 -0.00684444 -0.00852572  0.03100816 -0.03715711
   -0.00062443  0.016142   -0.03523703  0.00606283  0.0204481 ]
  [-0.01706602 -0.00684444 -0.00852572  0.03100816 -0.03715711
   -0.00062443  0.016142   -0.03523703  0.00606283  0.0204481 ]
  [-0.01706602 -0.00684444 -0.00852572  0.03100816 -0.03715711
   -0.00062443  0.016142   -0.03523703  0.00606283  0.0204481 ]
  [-0.01706602 -0.00684444 -0.00852572  0.03100816 -0.03715711
   -0.00062443  0.016142   -0.03523703  0.00606283  0.0204481 ]
  [-0.04375752  0.02850449 -0.00939532 -0.04981552  0.01845688
   -0.01247985  0.03557391 -0.04026928 -0.0461489   0.02904593]
  [-0.02123758 -0.01897678 -0.04072477 -0.02436051 -0.02274488
   -0.01349498 -0.02943944 -0.01835497  0.02163801 -0.04616593]
  [ 0.00473262 -0.01543476  0.04057935 -0.02605038 -0.02686458
    0.03488601 -0.00950308  0.04772831 -0.02851856 -0.00080398]
  [ 0.04205021  0.01947235 -0.04407917  0.03961047 -0.04581171
   -0.01329968 -0.03207155  0.00970135 -0.010072

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0, 7975, 6669, 9441, 2948], dtype=int32)

In [28]:
print(model.predict(embedded_docs)[0])

[[-0.01706602 -0.00684444 -0.00852572  0.03100816 -0.03715711 -0.00062443
   0.016142   -0.03523703  0.00606283  0.0204481 ]
 [-0.01706602 -0.00684444 -0.00852572  0.03100816 -0.03715711 -0.00062443
   0.016142   -0.03523703  0.00606283  0.0204481 ]
 [-0.01706602 -0.00684444 -0.00852572  0.03100816 -0.03715711 -0.00062443
   0.016142   -0.03523703  0.00606283  0.0204481 ]
 [-0.01706602 -0.00684444 -0.00852572  0.03100816 -0.03715711 -0.00062443
   0.016142   -0.03523703  0.00606283  0.0204481 ]
 [-0.04375752  0.02850449 -0.00939532 -0.04981552  0.01845688 -0.01247985
   0.03557391 -0.04026928 -0.0461489   0.02904593]
 [-0.02123758 -0.01897678 -0.04072477 -0.02436051 -0.02274488 -0.01349498
  -0.02943944 -0.01835497  0.02163801 -0.04616593]
 [ 0.00473262 -0.01543476  0.04057935 -0.02605038 -0.02686458  0.03488601
  -0.00950308  0.04772831 -0.02851856 -0.00080398]
 [ 0.04205021  0.01947235 -0.04407917  0.03961047 -0.04581171 -0.01329968
  -0.03207155  0.00970135 -0.01007297  0.0364295 ]]